//laguages const
//spanish
const es = {
  menu1:"DIVISIONES",
  menu2:"UBICACIONES",
  menu3:"DE LA DIRECCIÓN GENERAL",
  menu4:"CONTACTO",
  menu5:"<img class=flaglang img-fluid src=images/es.png>",
  welcome:"Bienvenido",
  slide:"Desde 1975 nuestros expertos proveen las mejores soluciones",
  about:"Quiénes somos",
  abouttext:"Econométrica® es una organización consultora internacional altamente dinámica, donde colaboran expertos del más alto perfil profesional, técnico y académico; con nexos en diferentes partes del mundo. En ella laboran generadores de una mejor gerencia gubernamental y privada– que se traduce en oportunidades para el desarrollo, quienes se encuentran a su servicio.",
  ourdivisions:"Nuestras divisiones",
  private:"Sector Privado",
  public:"Sector Público",
  ti:"Sector Tecnologías de la Información",
  international:"Nuestra Red Internacional",
  Washington:"Washington DC",
  Beijing:"Beijing",
  Moscow:"Moscow",
  Munich:"Munich",
  Tokio:"Tokio",
  London:"London",
  Mexicoc:"Ciudad de México",
  BuenosA:"Buenos Aires",
  footer1:"Consulte su oficina local de <img class=imtxt img-fluid src=images/logotx.png> para conocer a fondo los detalles de cada una de nuestras divisiones y cómo le serán de utilidad.",
  footer2:"Nuestras Distinciones",
  footer3:"Pasantías",
  footer4:"Términos y condiciones",
  footer5:"Contacto",
  textdiv:"NUESTROS EXPERTOS PORVEEN LAS MEJORES SOLUCIONES EN LOS SIGUIENTES DIVISIONES:",
  privatetext:"- Soluciones Administrativas y &nbsp;&nbsp; Financieras  <br/>  - Soluciones de Eficiencia Tributaria    <br/>    - Consultoría Corporativa <br/> - Liderazgo Global y Estrategias <br/> - Estandarización",
  publictext:"- Finanzas Públicas <br>- Soluciones de Eficiencia Tributaria <br>- Ingresos Públicos Adicionales <br>- Política Pública <br>- Reingeniería de Procesos <br>- Relaciones Públicas <br>- Gobierno Electrónico <br>",
  titext:"- Fábrica de Software <br>- Sistemas Inteligentes <br> ",
  ceotext1:"De la Dirección General",
  ceotext2:"GRACIAS POR SU INTERÉS EN <img class=imtxt img-fluid src=images/logotxi2.png>",
  ceotext3:"Este año conmemoramos un año más de servicio ininterrumpido y lo queremos celebrar de la mejor manera posible: ofreciéndole las mejores soluciones. <br>  Nuestras estrategias altamente especializadas y basadas en sus necesidades nos han llevado a ocupar un preponderante lugar dentro de las preferencias del mercado. <br>Esperamos encuentre en nuestro portal electrónico la información que usted necesita para comenzar a resolver sus necesidades. Para mayor información acerca de nuestros servicios, no dude en contactarnos a través de su oficina local o de nuestras oficinas centrales en Washington, D.C. Con gusto le ayudaremos. <br> <br> Saludos cordiales, ",
  ceotext4:" Dr. Naomi Yamada <br> Directora General",
  contact1:"Contacto",
  contact2:"Si desea más información escríbanos, será un gusto atenderle. <br> No olvide incluir su(s) teléfono(s) y correo electrónico.",
  contact3:"Nombre",
  contact4:"Ingrese su nombre completo",
  contact5:"Título",
  contact6:"Escriba el motivo de su mensaje",
  contact7:"Correo Electrónico",
  contact8:"Escriba su correo electrónico",
  contact9:"Compañía",
  contact10:"Escriba el nombre de su Compañía",
  contact11:"País",
  contact12:"Mensaje",
  contact13:"Escriba su mensaje aquí",
  contact14:"Enviar",
  contact15:"Cancelar",
  distinction1:"Distinciones recibidas",
  distinction2:"Gracias a su calidad, diligencia y profesionalismo, nuestros expertos han recibido diversas distinciones, incluyendo:  <br>",
  distinction3:"<i> “Outstanding Intellectuals of the 21st Century”</i>",
  distinction4:"Por parte del prestigiado <i>International Biographical Center.</i>  <br>  (Cambridge, Reino Unido)",
  distinction5:"<i> “Man of the year”</i>",
  distinction6:"<i>“based on the outstanding accomplishments to date (…)”</i> <br> Por parte del internacionalmente reconocido <i> American Biographical Institute</i> (EE.UU.)",
  distinction7:"“Premio Nacional”",
  distinction8:"Por su “brillante trayectoria e interés en el estudio y planteamiento de la solución a los problemas políticos, sociales y económicos de nuestro país”.  ",
  distinction9:"Así como varios premios estatales <br> “al realizar de manera sobresaliente las actividades de investigación, políticas, sociales, de desarrollo comunitario…”",
  internship1:"Programa de Pasantías",
  internship2:"<img class=imtxt img-fluid src=images/logotxi2.png> organiza una jornada de puertas abiertas para las personas que desean hacer una carrera emocionante con nosotros. <br> Por lo general, estas personas comienzan como pasantes y, según sus aptitudes, comienzan a ser promovidos. Graduados en Informática (TI), Economía, Actuaría, Finanzas, MBA, Medios de Comunicación y Desarrollo Sustentable; así como otros candidatos con títulos avanzados (preferiblemente de una universidad ubicada en el hemisferio norte de cualquier continente) que tengan experiencia empresarial y analítica relevante y rigurosa, pueden unirse a nosotros. Un puntaje TOEFL iBT de 110 o más es obligatorio (si su idioma nativo no es inglés). ¡Únete a nuestra empresa internacional! Simplemente envíenos su currículum en el cuerpo del correo electrónico (en inglés, no más de una página. NO se aceptan archivos adjuntos) a: contact@econometrica.info <br> Nuestro programa de pasantías está abierto para solicitantes durante todo el año. <br> Debido al gran volumen de solicitudes que recibimos, nos pondremos en contacto sólo con aquellas personas en las que nuestras oficinas locales estén interesadas.",
  term1:"Términos y Condiciones",
  term2:"lorem",

}
//english
const en = {
  menu1:"DIVISIONS",
  menu2:"LOCATIONS",
  menu3:"FROM OUR CEO",
  menu4:"CONTACT US",
  menu5:"<img class=flaglang img-fluid src=images/en.png>",
  welcome:"WELCOME",
  slide:"Since 1975 our experts provide our customers with the best solutions",
  about:"About us",
  abouttext:"<img class=imtxt img-fluid src=images/logotxi.png> is a highly dynamic international consulting organization, where experts from the highest professional, technical and academic background collaborate, with a worldwide perspective. In <img class=imtxt img-fluid src=images/logotxi.png> work creators of better management –governmental and private– that translates into opportunities for development, at your service! Contact your local <img class=imtxt img-fluid src=images/logotxi.png> office to learn more about the details of each of our divisions and how they will be useful.",
  ourdivisions:"Divisions",
  private:"Private Sector",
  public:"Public Sector",
  ti:"Information Technology Sector",
  international:"Our International Network",
  Washington:"Washington DC",
  Beijing:"Beijing",
  Moscow:"Moscow",
  Munich:"Munich",
  Tokio:"Tokyo",
  London:"London",
  Mexicoc:"Mexico City",
  BuenosA:"Buenos Aires",
  footer1:"Consult your local <img class=imtxt img-fluid src=images/logotxi.png> office for details of each of our divisions and how they will be useful.",
  footer2:"Awards",
  footer3:"Internships",
  footer4:"Terms and Conditions",
  footer5:"Contact us",
  textdiv:"OUR EXPERTS PROVIDE THE BEST SOLUTIONS IN THE FOLLOWING DIVISIONS:",
  privatetext:"- Administrative and Financial Solutions <br>- Corporate Consulting <br>- Global Leadership and Strategies<br> - Standardization",
  publictext:"- Public finances <br>- Tax Efficiency Solutions <br>- Additional Public Income <br> - Public politics- Process reengineering <br>- Public relations <br>- Electronic Government",
  titext:"- Software Factory <br> - Intelligent Systems",
  ceotext1:"From Our Ceo",
  ceotext2:"Thank you for your interest in <img class=imtxt img-fluid src=images/logotxi2.png>",
  ceotext3:" We celebrate another year of uninterrupted service and we want to celebrate it in the best possible way: offering you the best solutions. <br> Our highly specialized strategies based on your needs have led us to occupy a prominent place within the market. <br> We hope to find in our electronic portal the information you need to start solving your needs. For more information about our services, do not hesitate to contact us through your local office or our headquarters in Washington, D.C. We will gladly help you. <br> <br>Best regards,  <br> ",
  ceotext4:" Dr. Naomi Yamada <br> CEO",
  contact1:"Contact",
  contact2:"If you want more information write to us, it will be a pleasure to assist you. <br> don't forget to include your phone number and email.",
  contact3:"Name",
  contact4:"Write your name",
  contact5:"Title",
  contact6:"Enter your message reason",
  contact7:"E-mail",
  contact8:"Enter your email address",
  contact9:"Company name",
  contact10:"Enter your Company name",
  contact11:"Country",
  contact12:"Message",
  contact13:"Write your message here",
  contact14:"Send",
  contact15:"Cancel",
  distinction1:"Distinctions received",
  distinction2:"Thanks to its quality, diligence and professionalism, our experts have received various distinctions, including: <br>",
  distinction3:"<i> “Outstanding Intellectuals of the 21st Century”</i>",
  distinction4:"By the prestigious <i>International Biographical Center.</i>  <br> (Cambridge, United Kingdom)",
  distinction5:"<i> “Man of the year”</i>",
  distinction6:"<i>“Based on the outstanding accomplishments to date (…)”</i> <br> By the internationally recognized  <i> American Biographical Institute</i> (EE.UU.)",
  distinction7:"“National award”",
  distinction8:"For his “brilliant career and interest in the study and approach of the solution to the political, social and economic problems of our country.”",
  distinction9:"As well as various State Awards <br> “By carrying out outstanding research, political, social, community development activities…”",
  internship1:"Internship Program",
  internship2:"<img class=imtxt img-fluid src=images/logotxi2.png> organizes an open day for people who want to make an exciting career with us.<br> Usually, these people begin as interns and, according to their skills, begin to be promoted. <br> Graduates in Computer Science (IT), Economics, Actuary, Finance, MBA, Media and Sustainable Development; as well as other candidates with advanced degrees (preferably from a university located in the northern hemisphere of any continent) who have relevant and rigorous business and analytical experience, can join us. <br> A TOEFL iBT score of 110 or more is mandatory (if your native language is not English). <br> Join our international company! Simply send us your resume in the body of the email (in English, no more than one page. NO attachments are accepted) to: contact@econometrica.info <br> Our internship program is open to applicants throughout the year. <br> Due to the large volume of requests we receive, we will contact only those people in whom our local offices are interested.",
  term1:"Terms and Conditions",
  term2:"lorem",

}
//Russian
const ru = {
  menu1:"Разделы",
  menu2:"Места",
  menu3:"От нашего генерального директора",
  menu4:"Свяжитесь с нами",
  menu5:"<img class=flaglang img-fluid src=images/ru.png>",
  welcome:"Добро пожаловать",
  slide:"С 1975 года наши специалисты предоставляют нашим клиентам лучшие решения.",
  about:"НАСЧЕТ НАС",
  abouttext:"<img class=imtxt img-fluid src=images/logotxi.png> - это динамично развивающаяся международная консалтинговая организация, в которой сотрудничают специалисты с высочайшим профессиональным, техническим и академическим образованием, с перспективой во всем мире. В <img class=imtxt img-fluid src=images/logotxi.png> работают создатели лучшего управления - правительственного и частного - что открывает возможности для развития к вашим услугам! Свяжитесь с местным офисом <img class=imtxt img-fluid src=images/logotxi.png>, чтобы узнать больше о деталях каждого из наших подразделений и о том, как они будут полезны.",
  ourdivisions:"ПОДРАЗДЕЛЕНИЯ",
  private:"ЧАСТНЫЙ СЕКТОР",
  public:"ОБЩЕСТВЕННЫЙ СЕКТОР",
  ti:"СЕКТОР ИНФОРМАЦИОННЫХ ТЕХНОЛОГИЙ",
  international:"НАША МЕЖДУНАРОДНАЯ СЕТЬ",
  Washington:"Вашингтон",
  Beijing:"Пекин",
  Moscow:"Москва",
  Munich:"Мюнхен",
  Tokio:"Токио",
  London:"Лондон",
  Mexicoc:"Мехико",
  BuenosA:"Буэнос-Айрес",
  footer1:"Проконсультируйтесь с вашим местным <img class=imtxt img-fluid src=images/logotxi.png> офис для деталей каждого из наших подразделений и как они будут полезны.",
  footer2:"Награды",
  footer3:"Стажировки",
  footer4:"Условия и положения",
  footer5:"Свяжитесь с нами",
  textdiv:"Наши специалисты предоставляют лучшие решения в следующих подразделениях:",
  privatetext:"- Административные и финансовые решения <br> - Корпоративный консалтинг <br>- Глобальное лидерство и стратегии <br> - Стандартизация",
  publictext:"- Государственные финансы <br>- Решения по налоговой эффективности <br> - Дополнительный публичный доход <br> - публичная политика <br>- процесс реинжиниринга <br>- Связи с общественностью <br>- Электронное правительство <br>",
  titext:"- Фабрика программного обеспечения <br>- Интеллектуальные Системы",
  ceotext1:"ОТ НАШЕГО СЕКТОРА",
  ceotext2:"Благодарим Вас за интерес к  <img class=imtxt img-fluid src=images/logotxi2.png>",
  ceotext3:" Мы отмечаем еще один год бесперебойного обслуживания, и мы хотим отпраздновать его наилучшим образом: предлагая вам лучшие решения. <br> Наши высокоспециализированные стратегии, основанные на ваших потребностях, позволили нам занять видное место на рынке. <br> Мы надеемся найти на нашем электронном портале информацию, необходимую для решения ваших задач. Для получения дополнительной информации о наших услугах, не стесняйтесь обращаться к нам через ваш местный офис или нашу штаб-квартиру в Вашингтоне, округ Колумбия. Мы с радостью поможем вам. <br> С уважением, ",
  ceotext4:" Доктор Наоми Ямада <br>Исполнительный директор",
  contact1:"СВЯЖИТЕСЬ С НАМИ",
  contact2:"Если вы хотите получить больше информации, напишите нам, мы с удовольствием вам поможем. Не забудьте указать свой номер телефона и адрес электронной почты.",
  contact3:"имя",
  contact4:"Напиши свое имя",
  contact5:"заглавие",
  contact6:"Введите причину вашего сообщения",
  contact7:"электронное письмо",
  contact8:"Введите адрес электронной почты",
  contact9:"Компания",
  contact10:"Enter the name of your Company",
  contact11:"Введите название вашей компании",
  contact12:"Сообщение",
  contact13:"Напишите ваше сообщение здесь",
  contact14:"послать",
  contact15:"Отмена",
  distinction1:"ОТЛИЧИЯ, ПОЛУЧЕННЫЕ",
  distinction2:"Благодаря его качеству, трудолюбию и профессионализму наши специалисты получили различные отличия, в том числе: <br>",
  distinction3:"<i> «Выдающиеся интеллектуалы XXI века»</i>",
  distinction4:"У престижного Международного <i>биографического центра.</i>  <br> (Кембридж, Великобритания)",
  distinction5:"<i> «Человек года»</i>",
  distinction6:"<i>«На основании выдающихся достижений на сегодняшний день (…)»</i> <br> Всемирно признанный  <i> Американский Биографический Институт</i> (США)",
  distinction7:"«Национальная премия»”",
  distinction8:"За его «блестящую карьеру и интерес к изучению и подходу к решению политических, социальных и экономических проблем нашей страны».",
  distinction9:"А также различные государственные награды <br> «Проводя выдающиеся исследования, политические, социальные, общественно-полезные мероприятия…»",
  internship1:"ПРОГРАММА ИНТЕРНАТУРЫ",
  internship2:"<img class=imtxt img-fluid src=images/logotxi2.png> организует день открытых дверей для людей, которые хотят сделать с нами интересную карьеру. <br> Обычно эти люди начинают работать в качестве стажеров и, в соответствии с их навыками, начинают продвигаться по службе. <br>Выпускники в области компьютерных наук (ИТ), экономики, актуарий, финансы, MBA, СМИ и устойчивого развития; К нам могут присоединиться и другие кандидаты с учеными степенями (предпочтительно из университета, расположенного в северном полушарии любого континента), которые имеют соответствующий и строгий опыт работы в сфере бизнеса и аналитики. <br>Оценка TOEFL iBT 110 или более обязательна (если ваш родной язык не английский). <br>Присоединяйтесь к нашей международной компании! Просто отправьте нам свое резюме в теле письма (на английском языке, не более одной страницы. Вложения не принимаются) по адресу: contact@econometrica.info <br> Наша программа стажировки открыта для кандидатов в течение всего года. <br>  Из-за большого объема запросов, которые мы получаем, мы свяжемся только с теми людьми, в которых заинтересованы наши местные офисы.",
  term1:"Условия и положения",
  term2:"lorem",
 }
 //chinese
 const zh = {
  menu1:"师",
  menu2:"地点",
  menu3:"来自我们的总监",
  menu4:"联系我们",
  menu5:"<img class=flaglang img-fluid src=images/zh.png>",
  welcome:"欢迎",
  slide:"自1975年以来，我们的专家为客户提供了最佳的解决方案。",
  about:"关于我们",
  abouttext:"<img class=imtxt img-fluid src=images/logotxi.png> 是一个高度动态的国际咨询组织，具有最高专业，技术和学术背景的专家可以在全球范围内进行合作。 在<img class=imtxt img-fluid src=images/logotxi.png> 中，为政府和私营部门提供更好管理的创造者可以为您服务，为他们带来发展机会！请与您当地的 <img class=imtxt img-fluid src=images/logotxi.png> 办公室联系，以了解有关我们每个部门的详细信息以及它们将如何发挥作用的更多信息",
  ourdivisions:"部门",
  private:"私营部门",
  public:"公共部门",
  ti:"信息技术行业",
  international:"我们的国际网络",
  Washington:"华盛顿特区",
  Beijing:"北京",
  Moscow:"莫斯科",
  Munich:"慕尼黑",
  Tokio:"东京",
  London:"伦敦",
  Mexicoc:"墨西哥城",
  BuenosA:"布宜诺斯艾利斯市",
  footer1:"请咨询您当地的 <img class=imtxt img-fluid src=images/logotxi.png> 办事处，以了解我们每个部门的详细信息以及它们如何发挥作用。",
  footer2:"获奖情况",
  footer3:"实习机会",
  footer4:"条款和条件",
  footer5:"联系我们",
  textdiv:"我们的专家在以下部门提供最佳解决方案：",
  privatetext:"-行政和财务解决方案 <br>-企业咨询 <br>-全球领导力和策略<br> -标准化",
  publictext:"-公共财政<br>-税收效率解决方案<br>-额外的公共收入<br> -公共政治 <br>-流程再造 <br>- 公共关系<br>-电子政务",
  titext:"-软件工厂<br> -智能系统",
  ceotext1:"来自我们的首席执行官",
  ceotext2:"感谢您对 <img class=imtxt img-fluid src=images/logotxi2.png> 的关注。",
  ceotext3:"我们庆祝服务不中断的又一年，我们希望以最好的方式庆祝：为您提供最佳解决方案。 <br> 我们根据您的需求提供高度专业化的策略，从而使我们在市场中占据重要地位。<br> 我们希望在我们的电子门户网站中找到开始解决需求所需的信息。有关我们服务的更多信息，请随时通过您当地的办公室或我们位于华盛顿特区的总部与我们联系。我们将竭诚为您服务。 <br> <br>最好的祝福，<br> ",
  ceotext4:"山田直美博士 <br> 首席执行官",
  contact1:"联系我们",
  contact2:"如果您需要更多信息给我们，我们将很乐意为您提供帮助。<br> 不要忘记包括您的电话号码和电子邮件。",
  contact3:"名称",
  contact4:"写你的名字",
  contact5:"标题",
  contact6:"输入留言原因",
  contact7:"电子邮件",
  contact8:"输入您的电子邮件地址",
  contact9:"公司名",
  contact10:"输入您的公司名称",
  contact11:"国家",
  contact12:"信息",
  contact13:"在这里写下您的讯息",
  contact14:"发送",
  contact15:"取消",
  distinction1:"收到的区别",
  distinction2:"凭借其高质量，勤奋和专业的精神，我们的专家获得了许多殊荣，包括： <br>",
  distinction3:"<i> “二十一世纪杰出知识分子”</i>",
  distinction4:"由著名的国际传记中心提供。  <br> （英国剑桥）",
  distinction5:"<i> “年度人物”</i>",
  distinction6:"<i>“基于迄今为止的杰出成就（...）”</i> <br> 由国际公认的美国传记研究所（美国）",
  distinction7:"“国家奖”",
  distinction8:"“以他的杰出事业和对研究我国政治，社会和经济问题的研究方法的兴趣。”",
  distinction9:"以及各种州奖 <br> “通过开展出色的研究，政治，社会，社区发展活动……”",
  internship1:"实习计划",
  internship2:"<img class=imtxt img-fluid src=images/logotxi2.png>为希望与我们一起事业振奋的人们举办开放日。<br> 通常，这些人是从实习生开始的，并根据他们的技能开始得到提升。<br>计算机科学（IT），经济学，精算师，金融，MBA，媒体和可持续发展专业的毕业生；以及其他具有相关且严格的业务和分析经验的高级学位候选人（最好是来自任何大洲北半球的一所大学）都可以加入我们。. <br> TOEFL iBT分数必须达到110分或更高（如果您的母语不是英语）。 <br> 加入我们的国际公司！只需通过电子邮件正文将您的简历发送给我们（英文，最多一页，不接受附件）至：contact@econometrica.info<br>我们的实习计划全年对申请人开放。 <br> 由于我们收到大量请求，因此我们将仅与当地办事处感兴趣的人员联系。",
  term1:"条款和条件",
  term2:"lorem",

}
//German
const de = {
  menu1:"Abteilungen",
  menu2:"Standorte",
  menu3:"Von unserem CEO",
  menu4:"Kontaktiere uns",
  menu5:"<img class=flaglang img-fluid src=images/de.png>",
  welcome:"WILLKOMMEN",
  slide:"Seit 1975 bieten unsere Experten unseren Kunden die besten Lösungen.",
  about:"ÜBER UNS",
  abouttext:"<img class=imtxt img-fluid src=images/logotxi.png> ist eine hochdynamische internationale Beratungsorganisation, in der Experten mit höchstem fachlichem, technischem und akademischem Hintergrund mit einer weltweiten Perspektive zusammenarbeiten. In <img class=imtxt img-fluid src=images/logotxi.png> arbeiten Schöpfer eines besseren Managements - staatlich und privat -, das sich in Entwicklungsmöglichkeiten zu Ihren Diensten niederschlägt! Wenden Sie sich an Ihr lokales  <img class=imtxt img-fluid src=images/logotxi.png> -Büro, um mehr über die Details der einzelnen Unternehmensbereiche und deren Nützlichkeit zu erfahren.",
  ourdivisions:"ABTEILUNGEN",
  private:"PRIVATER SEKTOR",
  public:"ÖFFENTLICHER SEKTOR",
  ti:"SEKTOR INFORMATIONSTECHNOLOGIE",
  international:"UNSER INTERNATIONALES NETZWERK",
  Washington:"Washington, D.C",
  Beijing:"Peking",
  Moscow:"Moskau",
  Munich:"München",
  Tokio:"Tokyo",
  London:"London",
  Mexicoc:"Mexiko Stadt",
  BuenosA:"Buenos Aires",
  footer1:"Wenden Sie sich an Ihr lokales  <img class=imtxt img-fluid src=images/logotxi.png>-Büro, um Informationen zu den einzelnen Geschäftsbereichen und deren Nützlichkeit zu erhalten.",
  footer2:"Auszeichnungen",
  footer3:"Praktika",
  footer4:"Geschäftsbedingungen",
  footer5:"Kontaktiere uns",
  textdiv:"Unsere Experten bieten die besten Lösungen in den folgenden Bereichen:",
  privatetext:"- Administrative und finanzielle Lösungen <br>- Unternehmensberatung <br>- Globale Führung und Strategien<br>- Standardisierung",
  publictext:"- Öffentliche Finanzen <br>- Steuereffizienzlösungen<br>- Zusätzliches öffentliches Einkommen<br>- Öffentliche Politik <br>- Prozessüberarbeitung <br>- Öffentlichkeitsarbeit<br>- Elektronische Regierung <br>",
  titext:"-Softwarefabrik <br>- Intelligente Systeme",
  ceotext1:"VON UNSEREM CEO",
  ceotext2:"Vielen Dank für Ihr Interesse an  <img class=imtxt img-fluid src=images/logotxi2.png>",
  ceotext3:"Wir feiern ein weiteres Jahr ununterbrochenen Service und möchten dies auf die bestmögliche Weise feiern: Wir bieten Ihnen die besten Lösungen. <br> Unsere hochspezialisierten Strategien, die auf Ihre Bedürfnisse zugeschnitten sind, haben dazu geführt, dass wir einen herausragenden Platz auf dem Markt einnehmen.<br>Wir hoffen, in unserem elektronischen Portal die Informationen zu finden, die Sie benötigen, um Ihre Anforderungen zu erfüllen. Wenn Sie weitere Informationen zu unseren Dienstleistungen wünschen, wenden Sie sich bitte über Ihr lokales Büro oder unseren Hauptsitz in Washington, DC, an uns. Wir helfen Ihnen gerne weiter. <br> <br>Freundliche Grüße,<br> ",
  ceotext4:" Dr. Naomi Yamada <br> CEO",
  contact1:"KONTAKTIERE UNS",
  contact2:"Wenn Sie weitere Informationen wünschen, schreiben Sie uns, wir helfen Ihnen gerne weiter. <br> Vergessen Sie nicht, Ihre Telefonnummer und Ihre E-Mail-Adresse anzugeben.",
  contact3:"Name",
  contact4:"Schreib deinen Namen",
  contact5:"Titel",
  contact6:"Geben Sie den Grund für Ihre Nachricht ein",
  contact7:"Email",
  contact8:"Geben sie ihre E-Mailadresse ein",
  contact9:"Name der Firma",
  contact10:"Geben Sie Ihren Firmennamen ein",
  contact11:"Land",
  contact12:"Botschaft",
  contact13:"Schreibe deine Nachricht hier",
  contact14:"Senden",
  contact15:"Stornieren",
  distinction1:"AUSZEICHNUNGEN ERHALTEN",
  distinction2:"Dank seiner Qualität, Sorgfalt und Professionalität haben unsere Experten verschiedene Auszeichnungen erhalten, darunter:<br>",
  distinction3:"<i> “Herausragende Intellektuelle des 21. Jahrhunderts”</i>",
  distinction4:"Vom renommierten <i>International Biographical Centre.</i>  <br> (Cambridge, Großbritannien)",
  distinction5:"<i> “Mann des Jahres”</i>",
  distinction6:"<i>“Basierend auf den bisherigen herausragenden Leistungen (…)”</i> <br> Vom international anerkannten   <i> American Biographical Institute</i> (USA)",
  distinction7:"“Nationaler Preis”",
  distinction8:"Für seine “glänzende Karriere und sein Interesse an der Erforschung und Herangehensweise der Lösung der politischen, sozialen und wirtschaftlichen Probleme unseres Landes”",
  distinction9:"Sowie diverse Staatspreise <br> „Indem wir herausragende Forschungs-, politische, soziale und Gemeindeentwicklungsaktivitäten durchführen…“",
  internship1:"PRAKTIKUMSPROGRAMM",
  internship2:"<img class=imtxt img-fluid src=images/logotxi2.png> organisiert einen Tag der offenen Tür für Menschen, die eine spannende Karriere bei uns machen möchten.<br> Normalerweise beginnen diese Personen als Praktikanten und werden entsprechend ihren Fähigkeiten befördert. <br> Absolventen in Informatik (IT), Wirtschaft, Versicherungsmathematik, Finanzen, MBA, Medien und Nachhaltige Entwicklung; Ebenso wie andere Kandidaten mit fortgeschrittenem Abschluss (vorzugsweise von einer Universität in der nördlichen Hemisphäre eines Kontinents), die über relevante und strenge geschäftliche und analytische Erfahrung verfügen, können sie sich uns anschließen. <br> Ein TOEFL iBT-Score von 110 oder mehr ist obligatorisch (wenn Ihre Muttersprache nicht Englisch ist). <br> Treten Sie unserem internationalen Unternehmen bei! Senden Sie uns einfach Ihren Lebenslauf im Hauptteil der E-Mail (auf Englisch, nicht mehr als eine Seite. Es werden KEINE Anhänge akzeptiert) an: contact@econometrica.info <br> Unser Praktikumsprogramm steht Bewerbern das ganze Jahr über offen. <br> Aufgrund der großen Anzahl von Anfragen, die wir erhalten, werden wir nur diejenigen Personen kontaktieren, an denen unsere lokalen Büros interessiert sind.",
  term1:"Geschäftsbedingungen",
  term2:"lorem",

}

//japanese
const ja = {
  menu1:"部門",
  menu2:"場所",
  menu3:"ディレクターから",
  menu4:"お問い合わせ",
  menu5:"<img class=flaglang img-fluid src=images/ja.png>",
  welcome:"ようこそ",
  slide:"1975年以来、当社の専門家はお客様に最高のソリューションを提供しています。",
  about:"私 私 た ち に 関 し て",
  abouttext:"<img class=imtxt img-fluid src=images/logotxi.png> は非常にダイナミックな国際コンサルティング組織であり、最高の専門的、技術的、学問的背景を持つ専門家が世界的な視野で協力しています。 <img class=imtxt img-fluid src=images/logotxi.png> では、より良い管理（政府および民間）のクリエーターが、あなたのサービスで開発の機会をもたらします！ 各部門の詳細とそれらがどのように役立つかについては、お近くの <img class=imtxt img-fluid src=images/logotxi.png> オフィスにお問い合わせください。",
  ourdivisions:"部門",
  private:"民間部門",
  public:"公的機関",
  ti:"情報技術部門",
  international:"私たちの国際ネットワーク",
  Washington:"ワシントンDC",
  Beijing:"北京",
  Moscow:"モスクワ",
  Munich:"ミュンヘン",
  Tokio:"東京",
  London:"ロンドン",
  Mexicoc:"メキシコシティ",
  BuenosA:"ブエノスアイレス市",
  footer1:"地元の <img class=imtxt img-fluid src=images/logotxi.png> に相談する 各部門の詳細とその有用性については、オフィスをご覧ください。",
  footer2:"受賞歴",
  footer3:"インターンシップ",
  footer4:"規約と条件",
  footer5:"お問い合わせ",
  textdiv:"当社の専門家は、次の部門で最高のソリューションを提供します。",
  privatetext:"-管理および金融ソリューション <dv>-コーポレートコンサルティング <dv>-グローバルリーダーシップと戦略 <dv>-標準化",
  publictext:"-財政 <dv>-税効率ソリューション <dv> -追加の公共収入 <dv> -公共政治 <dv> -プロセスのリエンジニアリング <dv>- 広報 <dv>-電子政府",
  titext:"-ソフトウェア工場 <br> -インテリジェントシステム",
  ceotext1:"CEOから",
  ceotext2:"<img class=imtxt img-fluid src=images/logotxi2.png>に関心をお寄せいただきありがとうございます。",
  ceotext3:"中断のないサービスをもう1年祝います。最高のソリューションを提供するという、可能な限り最高の方法で祝いたいのです。 <br> お客様のニーズに基づいた高度に専門化された戦略により、当社は市場内の重要な地位を占めるようになりました。<br> 電子ポータルで、ニーズの解決を開始するために必要な情報を見つけたいと考えています。サービスの詳細については、最寄りのオフィスまたはワシントンD.C.の本社からお気軽にお問い合わせください。喜んでお手伝いいたします。 <br> <br>宜しくお願いします、  <br> ",
  ceotext4:" 山田直美 <br> (CEO)",
  contact1:"お問い合わせ",
  contact2:"より多くの情報を私たちに書きたい場合、あなたを支援することは喜びです。 <br> 電話番号とメールアドレスを忘れずに入力してください。",
  contact3:"名前",
  contact4:"あなたの名前を書いてください",
  contact5:"タイトル",
  contact6:"メッセージの理由を入力してください",
  contact7:"Eメール",
  contact8:"メールアドレスを入力してください",
  contact9:"会社名",
  contact10:"会社名を入力してください",
  contact11:"国",
  contact12:"メッセージ",
  contact13:"ここにメッセージを書いてください",
  contact14:"送る",
  contact15:"キャンセル",
  distinction1:"受信した地区",
  distinction2:"その品質、勤勉さ、プロ意識のおかげで、当社の専門家は次のようなさまざまな区別を受けています。 <br>",
  distinction3:"<i> “「21世紀の優れた知識人」”</i>",
  distinction4:"有名な国際伝記センター。  <br> （イギリス、ケンブリッジ）",
  distinction5:"<i> “その年に最も活躍した人”</i>",
  distinction6:"<i>「これまでの顕著な成果に基づいて（…）」”</i> <br> 国際的に認められた<i> American Biographical Institute</i> （米国）",
  distinction7:"“「国家賞」”",
  distinction8:"わが国の政治的、社会的、経済的問題に対する解決策の研究とアプローチに対する素晴らしいキャリアと関心」。",
  distinction9:"さまざまな国家賞と同様に <br> 「優れた研究、政治、社会、コミュニティ開発活動を実施することにより…」",
  internship1:"インターンシッププログラム",
  internship2:"<img class=imtxt img-fluid src=images/logotxi2.png> は、私たちと一緒にエキサイティングなキャリアを築きたい人々のためにオープンデーを開催します。<br> 通常、これらの人々はインターンとして始まり、スキルに応じて昇進し始めます. <br> コンピューターサイエンス（IT）、経済学、アクチュアリー、ファイナンス、MBA、メディアおよび持続可能な開発の卒業生。関連する厳格なビジネスおよび分析の経験がある他の候補者（できれば大陸の北半球にある大学から）が参加できます。 <br> 110以上のTOEFL iBTスコアが必須です（母国語が英語でない場合）。<br> 国際企業に参加しましょう！電子メールの本文に履歴書を英語で送信してください（英語、1ページ以内。添付ファイルは不可）：contact@econometrica.info<br> 私たちのインターンシッププログラムは、年間を通して応募者に開放されています。 <br> 多数のリクエストが寄せられているため、ローカルオフィスに関心のある人にのみ連絡します。",
  term1:"条款和条件",
  term2:"lorem",

}
//add lenguages
const lenguajes = {es, en, ru, zh, de, ja, }
